# Generated by Django 2.2.4 on 2019-08-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.DecimalField(decimal_places=3, max_digits=6)),
                ('height', models.CharField(max_length=5)),
                ('health', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.Plot')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.Property'),
        ),
    ]
